services:
  plausible_db:
    image: postgres:14-alpine
    container_name: plausible-db
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: plausible
      POSTGRES_USER: plausible
      POSTGRES_PASSWORD: "${PLAUSIBLE_DB_PASSWORD}"

  plausible_events_db:
    image: clickhouse/clickhouse-server:23.3.7.5-alpine
    container_name: plausible-events-db
    restart: always
    volumes:
      - ./event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0.0
    container_name: plausible
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    environment:
      BASE_URL: https://analytics.polyfrost.org/
      SECRET_KEY_BASE: "${PLAUSIBLE_SECRET_KEY_BASE}"
      PORT: 80
      DATABASE_URL: "postgres://plausible:${PLAUSIBLE_DB_PASSWORD}@plausible-db:5432/plausible"
      CLICKHOUSE_DATABASE_URL: http://plausible-events-db:8123/plausible_events_db
      DISABLE_REGISTRATION: invite_only
      MAXMIND_LICENSE_KEY: "${MAXMIND_KEY}"

networks:
  default:
    name: external
    external: true
