version: "3"

services:
  caddy:
    image: polyfrost.org/caddy
    pull_policy: never
    container_name: caddy
    restart: always
    build:
      dockerfile: ./Dockerfile
      args:
        XCADDY_VERSION: 0.4.4
        CADDY_VERSION: 2.9.1
    volumes:
      - ./Caddyfile:/srv/caddy/Caddyfile
      - ./data:/srv/caddy/data
      - ./static:/srv/caddy/static
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        ipv4_address: 172.16.1.69

networks:
  default:
    name: external
    external: true
