version: "3"
services:
  backend:
    container_name: backend-rs
    build:
      dockerfile: Dockerfile
      context: ./repo
    restart: unless-stopped
    environment:
      PORT: 8080
      INTERNAL_MAVEN_URL: http://reposilite:8080
      PUBLIC_MAVEN_URL: https://repo.polyfrost.org

networks:
  default:
    external: true
    name: external
