version: "3.9"
services:
  reposilite:
    image: ghcr.io/dzikoysk/reposilite:3.5.12
    container_name: reposilite
    environment:
      JAVA_OPTS: -Xmx128M -Dtinylog.writerFile.level=off
      MEMORY: 128M
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: bash -c ":> /dev/tcp/127.0.0.1/8080 || exit 1"
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  default:
    external: true
    name: external
