# TODO replace with single CIDR declaration at the top that gets transformed into host, gateway, and services
# services can be declared in list and have ips autogenerated from cidr
{
    cidr = "172.25.0.0/24";
    host = "172.25.0.1";
    gateway = "172.25.0.255";

    postgres = "172.25.0.2";
    backend = "172.25.0.3";
    reposilite = "172.25.0.4";
    plausible = "172.25.0.5";
}
